### ISSUE TITLE
Matrix service button misleading

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/dcp-feedback#1]
The  "Request Expression Matrix" button is activated whenever there are *zarr files available to be collated, and the button is disabled otherwise. There are currently only 2 projects that produce *zarr file outputs.  There are other types of expression matrix output files though, and many other projects that have expression output data. The way the button is labeled leads the user to believe that there are no expression matrices for any of these other projects because the button is disabled due to the lack of *zarr files. But the Atlas does have expression matrices for lots of other data. 

Also, there is a new section in the Project view that lists the type of data available, with one column labeled "Matrix". This also only shows a count when there are *zarr files available. 

@gabsie @theathorn @brianraymor

**Comment by kozbo** [comment]
Note: this issue was created based on feedback through the Beta program and summarized by the UX team

**Comment by NoopDog** [comment]
test

**Comment by NoopDog** [comment]
This has been addressed by the updated "get data" flows.
