### ISSUE TITLE
Data browser overly sensitive to screen width

### ISSUE THREAD

**Issue by adriennes** [HumanCellAtlas/dcp-feedback#10]
The data browser readjusts depending on screen width, but it is so sensitive, and the UI change is so dramatic, that it is confusing to users (P9 in beta test)

The column "Data" and filters were affected in particular

**Comment by NoopDog** [comment]
We have opened two tickets to address the comments on the current responsive behavior and linked them as dependancies above.

**Comment by theathorn** [comment]
Issue fixed - please verify.

**Comment by NoopDog** [comment]
These changes are deployed to production. @adriennes Can this be closed?

**Comment by NoopDog** [comment]
implemented
