### ISSUE TITLE
Zip file won't open on .csv matrix download

### ISSUE THREAD

**Issue by adriennes** [HumanCellAtlas/dcp-feedback#12]
After requesting to download an expression matrix and selecting .csv as the output file format, the zip folder downloaded will not open.

**Comment by brianraymor** [comment]
@adriennes -  do you think that it may have actually be [this](https://github.com/HumanCellAtlas/matrix-service/issues/167)?

**Comment by adriennes** [comment]
Yes, this seems to be the same issue (Matrix Service #167)
Per the other bug, this seems like a file naming issue rather than actually not unzipping.  Will close this one out
