### ISSUE TITLE
Checkboxes needed in data browser

### ISSUE THREAD

**Issue by adriennes** [HumanCellAtlas/dcp-feedback#2]
Users looking through data in browser want to quickly select an item, but instead have to use search and/or filters to narrow list to one item.  

This is a major usability issue that has been raised repeatedly in testing and now in beta.  It will get more severe as we get more data in the DCP

**Comment by adriennes** [comment]
This came up for beta testers P7 and P9 - no ability to select single project in Projects view is frustrating

**Comment by kozbo** [comment]
related to #14

**Comment by NoopDog** [comment]
@adriennes checkboxes have beed deployed to prod. Is this ok to close?

**Comment by adriennes** [comment]
Thanks for doing this!  I think the way we've implemented these checkboxes is a little unexpected, though.  Usually checkboxes allow multiple select; this is also useful if a user wants to download and compare two datasets, for example. 

Instead of having all other projects disappear from the list once an item is selected, could we keep the view the same, and allow a user to select multiple items?

**Comment by NoopDog** [comment]
Yes, this is definitely on our roadmap and I think this is easier than I once thought. We have a ticket to track here: https://github.com/HumanCellAtlas/data-browser/issues/419

**Comment by NoopDog** [comment]
This is implemented
