### ISSUE TITLE
Portal contributors need way to review and edit info about tools/portals

### ISSUE THREAD

**Issue by adriennes** [HumanCellAtlas/dcp-feedback#3]
Portal contributors currently 1. aren't informed that their tools/portals will be listed on the Data Portal and 2. don't have a way to make their project description and links accurate and up to date. 

In beta testing, a tester saw her portal listed and was surprised.  She noted that we are listing the wrong url for her project.

**Comment by NoopDog** [comment]
@adriennes well, yes I am not sure what the process is to include a portal in the list perhaps @TimothyTickle or @eweitz can comment on that?

For item 2, 

>2. don't have a way to make their project description and links accurate and up to date.

users can create a pull request in github with any required updates or reach out to the help/contact to get updates made. There likely should be some training or an email describing the process when a portal is included. Who would be responsible for setting something like that up?

<img width="1131" alt="screen shot 2019-01-11 at 11 08 10 am" src="https://user-images.githubusercontent.com/3239697/51007014-878b3800-1591-11e9-9c40-02edefec0ca9.png">

**Comment by TimothyTickle** [comment]
Hey everyone, the listing of portals is not a part of the methods registry but part of the general support for the red box community. I believe, however, it makes sense to include these together as a user experience. I do not believe I remember how this section started but like that we have it :-).

If Dave is ok with it, I would advocate for using the same process that is set up for submitting to the methods registry which is a templated github PR. When we receive these PRs the information can be added (for now) in a manual way similar to the methods and visualizations where an internal member adds the data in markdown? Would this be something the content team does? Would love your thoughts (and please note you are not obligated to agree @jodihir).

Also, we need to make sure the groups know they are on the list, would you like me to contact each group so they are aware? Although I did not suggest them, I would expect to know them and can confirm they are comfortable with the current state of their listing.

**Comment by eweitz** [comment]
> I would advocate for using the same process that is set up for submitting to the methods registry which is a templated github PR

The current approach to adding a portal listing uses a GitHub issue template.  The same approach is used for submitting (i.e., creating) a method or visualization listing.  Those templates can be found at https://github.com/HumanCellAtlas/data-portal-content/tree/master/.github/ISSUE_TEMPLATE.  

Here's what the UI looks like for submitting a new portal listing:
<img width="960" alt="submit_your_portal_hca_data_browser_analyze_tab" src="https://user-images.githubusercontent.com/1334561/51044398-0337b580-158f-11e9-859c-072a922298c1.png">

There is a slight inconsistency here in that _creating_ a listing uses a templated GitHub issue, while _updating_ the entry uses a GitHub PR.  But creating and updating are slightly different use cases, so I think the slightly different approaches make sense.  

An issue template makes initial validation easier and helps ensure similar needed information is provided upon creation.  (A human maintainer in `data-portal-content` validates it and writes the initial Markdown, and does some mildly technical configuration.)  A PR flow makes editing those listings easier, and aligns with the UX for suggesting edits in other parts of the site.

> we need to make sure the groups know they are on the list

I've liaised with all the listed portal groups, and have been emailing each after listing their portal.  That said, given the recent significant design work, another follow-up might be a good way to remind them again and solicit feedback on our usability.

**Comment by NoopDog** [comment]
closing as these issues are resolved.
