### ISSUE TITLE
Matrix formats and uniform terminology

### ISSUE THREAD

**Issue by gabsie** [HumanCellAtlas/dcp-feedback#7]
P4 went through two different routes when trying to get to the expression matrix. 
1) She was guided by her knowledge of expected outputs for 10x, which is mtx or .matrix and went to explore file manifest, looking for familiar formats
2) for another project, she downloaded the matrix through a more intuitive to her process (active request a matrix button), however the format there - loom - was not familiar for her.

Scenario: the participant is simply after a matrix, and they expect a consistent matrix download behaviour, with a uniform "count matrix" label

Problem: no easy/consistent process or way to know that a matrix exists
Solution: uniform nomenclature or a link to the “count matrix” that would always go to the correct file, or give you options about the available file options below the label count matrix.

**Comment by brianraymor** [comment]
Regarding 2, we've added multiple formats now including .mtx, .loom, and .csv. Otherwise, this is UX feedback on discovering matrices. @theathorn - do you concur?

**Comment by theathorn** [comment]
I concur. 10x pipeline produces .mtx and .h5 files which are directly download-able but can't be passed to the Matrix Service. @brianraymor, @adriennes, @NoopDog - looking for suggestions on how best to improve the UX on this.

**Comment by NoopDog** [comment]
updated in prod
